# Generated by Django 4.1 on 2025-10-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('plazos_pago', models.CharField(help_text='Ej: 30 días', max_length=50)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('proveedor_preferente', models.BooleanField(default=False)),
                ('costo_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead_time', models.IntegerField(blank=True, help_text='Días de entrega', null=True)),
            ],
        ),
    ]
