# Generated by Django 5.1.7 on 2025-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
