# Generated by Django 5.1.7 on 2025-11-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_bodega_inventorymovement_lote_movementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='control_por_lote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_estandar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
