# Generated by assistant: fill missing Categoria values for Producto
from django.db import migrations


def create_default_category(apps, schema_editor):
    Categoria = apps.get_model('productos', 'Categoria')
    Producto = apps.get_model('productos', 'Producto')
    # Create or get default category
    cat, created = Categoria.objects.get_or_create(nombre_categoria='Sin categoría')
    # Assign to products without category
    Producto.objects.filter(categoria__isnull=True).update(categoria=cat)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_control_por_lote_producto_control_por_serie_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_category, reverse_code=noop),
    ]
