# Generated by assistant: alter categoria to be NOT NULL
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_fill_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=models.PROTECT, to='productos.categoria'),
        ),
    ]
