# Generated by Django 5.2.7 on 2025-10-15 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='razon_social',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números.')]),
        ),
    ]
