# Generated by Django 5.1.7 on 2025-10-21 03:06

import proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_razon_social_alter_proveedor_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_fantasia',
            new_name='razon_social',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, validators=[proveedores.models.validar_rut]),
        ),
    ]
