# Generated by Django 5.1.7 on 2025-11-18 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_rename_nombre_fantasia_proveedor_razon_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números.')]),
        ),
    ]
