# Generated by Django 5.1.7 on 2025-11-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_proveedor_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
